= Debugging: Keyring Issue =

:python:
:programming:

Whenever using `pip3 install --user <>` I got the following error:

{{{
Traceback (most recent call last):
  File "/home/berger/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/berger/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape
}}}

I was able to install packages using `sudo -H pip3 install ...` and using
`apt-get`. I solved this issue by removing all the keyring packages from apt and
the ones installed system-wide with pip so that in the end I ended up only with
the ones that were installed with `pip3 install --user` locally under
`~/.local`.

After this I ended up with the keyring blocked, that was expected though because
on that particular machine (my remote desktop machine that I was connecting
to via either VNC or simple SSH) I couldn't connect / unlock the gnome keyring
anyway.

<to-be-continued>


== Miscellaneous ==

* Another alternative that has worked for me in the past:
    * `pip3 install --upgrade keyrings.alt`
